name: Deploy to VM

on:
  push:
    branches:
      - master
      - develop

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Pull changes to the VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/kolosovpetro.github.io
            git checkout master
            git pull
            sudo nginx -t
            sudo systemctl restart nginx
            sudo nginx -t


