name: Deploy to VM

on:
  push:
    branches:
      - master
      - develop

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Artifact
        run: |
          zip -r website-artifact.zip .

      - name: Copy files to VM via SSH
        uses: nogsantos/scp-deploy@master
        with:
          src: website-artifact.zip
          host: ${{ secrets.SSH_HOST }}
          remote: "website-artifact-remote.zip"
          port: 22
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}

      - name: Extract artifact on Remote
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir -p temp_for_zip_extract
            unzip -o ~/website-artifact-remote.zip -d temp_for_zip_extract
